spring.application.name=D089_6May_LMS-ServerRelatedProperties

server.port=9000

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:port_number/lms_db
spring.datasource.username=YOUR_DB_USERNAME
spring.datasource.password=YOUR_DB_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.server.port=9090
management.endpoints.web.base-path=/manage
management.endpoints.web.exposure.include=health,beans,env,loggers,cache


